# permissions for end users to view firsts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: first-viewer-role
rules:
- apiGroups:
  - crds.my-domain.io
  resources:
  - firsts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crds.my-domain.io
  resources:
  - firsts/status
  verbs:
  - get
