apiVersion: v1
data:
  test.py: |-
    # Python program to find the factorial of a number provided by the user.

    # change the value for a different result
    num = 7

    factorial = 1

    # check if the number is negative, positive or zero
    if num < 0:
        print("Sorry, factorial does not exist for negative numbers")
    elif num == 0:
        print("The factorial of 0 is 1")
    else:
        for i in range(1,num + 1):
            factorial = factorial*i
        print("The factorial of",num,"is",factorial)
kind: ConfigMap
metadata:
  name: my-config-map-8bbkf8b4t2
---
apiVersion: v1
data:
  print.py: |-
    a = "Hello World !"
    b = "Working on building the first CRD"

    c = a + b
    print(c)
kind: ConfigMap
metadata:
  name: second-config-5g487cck6b
