
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: firsts.crds.my-domain.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.name
    name: InstanceName
    type: string
  - JSONPath: .spec.member
    name: Replica
    type: string
  group: crds.my-domain.io
  names:
    kind: First
    plural: firsts
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: First is the Schema for the firsts API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FirstSpec defines the desired state of First
          properties:
            container:
              description: Container Image
              properties:
                image:
                  type: string
              type: object
            member:
              description: Member describe the number of values
              format: int32
              type: integer
            name:
              description: Name
              type: string
          type: object
        status:
          description: FirstStatus defines the observed state of First
          properties:
            phase:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
